import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeftRight, Calculator, ChartNoAxesCombined, CircleHelp, Sparkles } from 'lucide-react';
import { ToolPage } from '@/components/tool-page';
import { getRequestLocale } from '@/lib/request-locale';
import { pageMetadata } from '@/lib/seo';

export const metadata: Metadata = pageMetadata('/huong-dan', 'Hướng dẫn sử dụng', 'Hướng dẫn từng bước để xem giá vàng, so sánh giá, quy đổi và tính hòa vốn trên Kim Tuyến.');

function guideTools(english: boolean) {
  return english ? [
    { id: 'bang-gia', icon: ChartNoAxesCombined, title: 'View today’s gold prices', summary: 'See dealer buy, dealer sell, and the trend for your selected period.', steps: ['Select a dealer and gold product above the price chart.', 'Choose 7 days, 1 month, or 1 year to view the trend.', 'Read dealer sell when buying; read dealer buy when selling.'], href: '/', action: 'Open price table' },
    { id: 'so-sanh', icon: ArrowLeftRight, title: 'Compare prices before trading', summary: 'Compare sources to find a price that fits your transaction.', steps: ['Choose Buying gold or Selling gold for the transaction you plan to make.', 'Choose a gold group and enter the quantity to buy or sell.', 'When buying, check the lowest dealer sell price; when selling, check the highest dealer buy price.'], href: '/cong-cu-vang#so-sanh', action: 'Open Gold Tools' },
    { id: 'quy-doi', icon: Calculator, title: 'Convert chỉ, lượng, and grams', summary: 'Convert common units while viewing or trading gold.', steps: ['Enter a quantity such as 2, then choose chỉ as the unit.', 'The result appears in lượng, chỉ, and grams.', 'A useful convention: 1 lượng = 10 chỉ = 37.5 grams.'], href: '/cong-cu-vang#hoa-von', action: 'Open Gold Tools' },
    { id: 'hoa-von', icon: Calculator, title: 'Calculate a no-loss selling price', summary: 'Find the price needed to recover your cost and fees.', steps: ['Enter the amount of gold and the price paid per lượng.', 'Enter fees when known; leave them empty if unknown.', 'Read Dealer buy price to break even and Estimated profit/loss.'], href: '/cong-cu-vang#hoa-von', action: 'Calculate break-even' },
  ] : [
    { id: 'bang-gia', icon: ChartNoAxesCombined, title: 'Xem giá vàng hôm nay', summary: 'Biết giá mua vào, giá bán ra và xu hướng trong khoảng thời gian bạn chọn.', steps: ['Chọn thương hiệu và loại vàng ở phía trên bảng giá.', 'Chọn 7 ngày, 1 tháng hoặc 1 năm để xem xu hướng.', 'Đọc “Giá bán ra” khi bạn muốn mua; đọc “Giá mua vào” khi bạn muốn bán.'], href: '/', action: 'Mở bảng giá' },
    { id: 'so-sanh', icon: ArrowLeftRight, title: 'So sánh giá trước khi giao dịch', summary: 'Đối chiếu nhiều nguồn để biết nơi nào đang có giá phù hợp hơn.', steps: ['Chọn “Mua vàng” hoặc “Bán vàng” đúng với việc bạn sắp làm.', 'Chọn nhóm vàng và nhập số lượng cần mua hoặc bán.', 'Xem giá thấp nhất khi mua, hoặc giá cao nhất khi bán.'], href: '/cong-cu-vang#so-sanh', action: 'Mở Công cụ vàng' },
    { id: 'quy-doi', icon: Calculator, title: 'Đổi chỉ, lượng và gram', summary: 'Đổi nhanh các đơn vị quen thuộc khi xem hoặc mua bán vàng.', steps: ['Nhập số lượng, ví dụ 2, rồi chọn đơn vị là “chỉ”.', 'Kết quả sẽ tự hiện theo lượng, chỉ và gram.', 'Quy ước dễ nhớ: 1 lượng = 10 chỉ = 37,5 gram.'], href: '/cong-cu-vang#hoa-von', action: 'Mở Công cụ vàng' },
    { id: 'hoa-von', icon: Calculator, title: 'Tính giá bán để không lỗ', summary: 'Biết mức giá cần bán để thu hồi tiền vốn và các khoản phí.', steps: ['Nhập số lượng vàng và giá bạn đã mua mỗi lượng.', 'Nhập phí nếu có; chưa biết phí thì có thể để trống.', 'Xem “Giá mua lại hòa vốn” và “Lãi/lỗ ước tính”.'], href: '/cong-cu-vang#hoa-von', action: 'Tính hòa vốn' },
  ];
}

export default async function GuidePage() {
  const locale = await getRequestLocale();
  const english = locale === 'en';
  const tools = guideTools(english);
  return <ToolPage eyebrow={english ? 'Start simply · Step-by-step examples' : 'Bắt đầu thật dễ · Có ví dụ từng bước'} title={english ? 'How to use Kim Tuyến' : 'Hướng dẫn sử dụng Kim Tuyến'} description={english ? 'You do not need technical knowledge. Choose the right tool and follow each step. Prices are informational; check with the dealer before trading.' : 'Bạn không cần rành công nghệ. Chỉ cần chọn đúng công cụ bên dưới và làm lần lượt từng bước. Giá chỉ mang tính tham khảo; hãy đối chiếu với cửa hàng trước khi giao dịch.'} showGuideLink={false}>
    <section className="glass-panel glass-panel--forest p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-primary/10"><CircleHelp className="size-5 text-primary" /></span><div><h2 className="font-heading text-xl font-semibold">{english ? 'What would you like to do?' : 'Bạn muốn làm gì?'}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{english ? 'Choose what is closest to your need. Every guide has only three short steps.' : 'Chọn mục gần với nhu cầu của bạn. Mỗi hướng dẫn chỉ gồm ba bước ngắn.'}</p></div></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{tools.map((tool) => <a key={tool.id} href={`#${tool.id}`} className="rounded-[16px] border border-border bg-card/70 p-3 text-sm font-semibold transition-colors hover:bg-card">{tool.title}</a>)}</div></section>
    <section id="cac-cong-cu" className="mt-8 space-y-4 scroll-mt-24">{tools.map((tool, index) => { const Icon = tool.icon; return <article key={tool.id} id={tool.id} className="glass-panel scroll-mt-24 p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-accent text-accent-foreground"><Icon className="size-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-accent-foreground">{english ? 'Guide' : 'Cách'} {index + 1}</p><h2 className="mt-1 font-heading text-xl font-semibold">{tool.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{tool.summary}</p></div></div><ol className="mt-5 grid gap-3 sm:grid-cols-3">{tool.steps.map((step, stepIndex) => <li key={step} className="rounded-xl border border-border bg-card/65 p-4 text-sm leading-6"><span className="mr-2 inline-grid size-6 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">{stepIndex + 1}</span><span>{step}</span></li>)}</ol><Link href={tool.href} className="mt-5 inline-flex min-h-11 items-center rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90">{tool.action}</Link></article>; })}</section>
    <section className="mt-8 glass-panel p-5 sm:p-7"><div className="flex items-start gap-3"><Sparkles className="mt-0.5 size-5 text-[var(--gold)]" /><div><h2 className="font-heading text-lg font-semibold">{english ? 'A few things to remember' : 'Một vài điều nên nhớ'}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-muted-foreground"><li>{english ? 'Kim Tuyến prices are references and can change over time.' : 'Giá trên Kim Tuyến là giá tham khảo và có thể thay đổi theo thời điểm.'}</li><li>{english ? 'Dealer buy is what the dealer pays you; dealer sell is what you pay the dealer.' : 'Giá mua vào là số tiền cửa hàng trả cho bạn; giá bán ra là số tiền bạn trả cho cửa hàng.'}</li><li>{english ? 'If anything is unclear, ask the dealer before confirming a trade.' : 'Nếu có điều gì chưa rõ, hãy hỏi lại cửa hàng trước khi chốt giao dịch.'}</li></ul></div></div></section>
    <section className="mt-8 glass-panel p-5 sm:p-7" aria-labelledby="guide-comparison-topics"><h2 id="guide-comparison-topics" className="font-heading text-lg font-semibold">{english ? 'Guides by comparison need' : 'Hướng dẫn theo nhu cầu so sánh'}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{english ? 'These pages explain how to read data for each product group.' : 'Các bài dưới đây giải thích cách đọc dữ liệu cho từng nhóm sản phẩm.'}</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/so-sanh/nhan-9999" className="rounded-full border border-border bg-card/70 px-4 py-2 text-sm font-semibold hover:bg-card">{english ? '9999 plain rings' : 'Nhẫn trơn 9999'}</Link><Link href="/so-sanh/vang-mieng-sjc" className="rounded-full border border-border bg-card/70 px-4 py-2 text-sm font-semibold hover:bg-card">{english ? 'SJC gold bars' : 'Vàng miếng SJC'}</Link><Link href="/so-sanh/nhan-9999-va-vang-mieng-sjc" className="rounded-full border border-border bg-card/70 px-4 py-2 text-sm font-semibold hover:bg-card">{english ? 'Compare rings and bars' : 'Đối chiếu nhẫn và miếng'}</Link></div></section>
  </ToolPage>;
}
